# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

workflows:
  version: 2.1
  test:
    jobs:
      - test-3_7
      - test-3_6
      # - test-3_8

jobs:
  test-3_7: &test-template
    docker:
      - image: circleci/python:3.7.5

    working_directory: ~/repo

    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #       - pymetabc-dependencies-pip-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "requirements-pip.txt" }}-{{ checksum "requirements-thirdparty.txt" }}
      #       - pymetabc-dependencies-pip-

      - run:
          name: update apt-get
          command: |
            sudo apt-get update
      - run:
          name: Setup Miniconda
          command: |
            sudo apt update
            sudo apt install -y wget
            cd $HOME
            wget "https://repo.anaconda.com/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh" -O miniconda.sh
            printf '%s' "8a324adcc9eaf1c09e22a992bb6234d91a94146840ee6b11c114ecadafc68121  miniconda.sh" | sha256sum -c
            bash miniconda.sh -b -p $HOME/miniconda
      - run:
          name: Setup environment and run tests
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            # conda update -y conda
            conda init bash
            conda config --add channels defaults
            conda config --add channels bioconda
            conda config --add channels conda-forge
            conda create -n pymetabc python=$PYTHON_VERSION
            conda activate pymetabc
            conda install -y --file requirements-dev.txt
            conda install -y --file requirements-thirdparty.txt
            conda install -y --file requirements.txt
            pip install -y -r requirements-pip.txt
            pip install -e .
            pytest -v --cov=pymetabc --cov-report xml:.coverage.xml
      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: pymetabc-dependencies-pip-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}-{{ checksum "requirements-pip.txt" }}-{{ checksum "requirements-thirdparty.txt" }}

      # - run:
      #     name: install pymetabc
      #     command: |
      #       . venv/bin/activate
      #       pip install -e .  # Install the repo as a package

      # - store_artifacts:
      #     path: tests/test_output/*.*
      #     destination: tests/test_output/
      - store_artifacts:
          path: .coverage.xml
          destination: .coverage.xml

      - codecov/upload:
          file: .coverage.xml

  test-3_6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6.8
  # test-3_8:
  #   <<: *test-template
  #   docker:
  #     - image: circleci/python:3.8.0
